image: node:12.14.1

before_script:
    - apt-get update
    - apt-get install zip --assume-yes
    - mkdir -p ~/.ssh
    - echo "$DEV_SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add <(echo "$DEV_SSH_PRIVATE_KEY")
    - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:
    - Publish_DEV
    - Publish_QA
    - Publish_STG
Publish_DEV:
    stage: Publish_DEV
    script:
        - echo -n "Deploying to DEV Server..."
        - zip -r build.zip *
        - ssh -p22 ubuntu@$DEV_SERVER_IP "mkdir -p ~/safe_com_mobile_api_tmp/ && rm -rf ~/safe_com_mobile_api_tmp/*"
        - scp build.zip ubuntu@$DEV_SERVER_IP:~/safe_com_mobile_api_tmp/
        - ssh -p22 ubuntu@$DEV_SERVER_IP "cd /var/www/html/safe_com_mobile_api && rm -rf node_modules/* && zip -r build_previous.zip *"
        - ssh -p22 ubuntu@$DEV_SERVER_IP "cd /var/www/html/backups && rm -rf build_previous.zip"
        - ssh -p22 ubuntu@$DEV_SERVER_IP "cd /var/www/html && mv safe_com_mobile_api/build_previous.zip backups/"
        - ssh -p22 ubuntu@$DEV_SERVER_IP "rm -rf /var/www/html/safe_com_mobile_api/* && unzip ~/safe_com_mobile_api_tmp/build.zip -d /var/www/html/safe_com_mobile_api/"
        - ssh -p22 ubuntu@$DEV_SERVER_IP "cd /var/www/html/safe_com_mobile_api && yarn install"
        - ssh -p22 ubuntu@$DEV_SERVER_IP "cd /var/www/html/safe_com_mobile_api && if pm2 list | grep safecommobile-dev; then pm2 restart safecommobile-dev; else pm2 start --name safecommobile-dev \"yarn server:pre-qa\"; fi"
    only:
        - RELEASE_DEV
    when: manual

Publish_QA:
    stage: Publish_QA
    script:
        - echo -n "Deploying to QA Server..."
        - zip -r build.zip *
        - ssh-add <(echo "$QA_SSH_PRIVATE_KEY")
        - ssh -p22 ubuntu@$QA_SERVER_IP "mkdir -p ~/safe_com_mobile_api_tmp/ && rm -rf ~/safe_com_mobile_api_tmp/*"
        - scp build.zip ubuntu@$QA_SERVER_IP:~/safe_com_mobile_api_tmp/
        - ssh -p22 ubuntu@$QA_SERVER_IP "cd /var/www/html/safe_com_mobile_api && rm -rf node_modules/* && zip -r build_previous.zip *"
        - ssh -p22 ubuntu@$QA_SERVER_IP "cd /var/www/html/backups && rm -rf build_previous.zip"
        - ssh -p22 ubuntu@$QA_SERVER_IP "cd /var/www/html && mv safe_com_mobile_api/build_previous.zip backups/"
        - ssh -p22 ubuntu@$QA_SERVER_IP "rm -rf /var/www/html/safe_com_mobile_api/* && unzip ~/safe_com_mobile_api_tmp/build.zip -d /var/www/html/safe_com_mobile_api/"
        - ssh -p22 ubuntu@$QA_SERVER_IP "cd /var/www/html/safe_com_mobile_api && yarn install"
        - ssh -p22 ubuntu@$QA_SERVER_IP "cd /var/www/html/safe_com_mobile_api && if pm2 list | grep safecommobile-qa; then pm2 restart safecommobile-qa; else pm2 start --name safecommobile-qa \"yarn server:qa\"; fi"
    only:
        - RELEASE_QA
    when: manual

Publish_STG:
    stage: Publish_STG
    script:
        - echo -n "Deploying to STG Server..."
        - zip -r build.zip *
        - ssh-add <(echo "$STG_SSH_PRIVATE_KEY")
        - ssh -p22 ubuntu@$STG_SERVER_IP "mkdir -p ~/safe_com_mobile_api_tmp/ && rm -rf ~/safe_com_mobile_api_tmp/*"
        - scp build.zip ubuntu@$STG_SERVER_IP:~/safe_com_mobile_api_tmp/
        - ssh -p22 ubuntu@$STG_SERVER_IP "cd /var/www/html/safe_com_mobile_api && rm -rf node_modules/* && zip -r build_previous.zip *"
        - ssh -p22 ubuntu@$STG_SERVER_IP "cd /var/www/html/backups && rm -rf build_previous.zip"
        - ssh -p22 ubuntu@$STG_SERVER_IP "cd /var/www/html && mv safe_com_mobile_api/build_previous.zip backups/"
        - ssh -p22 ubuntu@$STG_SERVER_IP "rm -rf /var/www/html/safe_com_mobile_api/* && unzip ~/safe_com_mobile_api_tmp/build.zip -d /var/www/html/safe_com_mobile_api/"
        - ssh -p22 ubuntu@$STG_SERVER_IP "cd /var/www/html/safe_com_mobile_api && yarn install"
        - ssh -p22 ubuntu@$STG_SERVER_IP "cd /var/www/html/safe_com_mobile_api && if pm2 list | grep safecommobile-stg; then pm2 restart safecommobile-stg; else pm2 start --name safecommobile-stg \"yarn server:stg\"; fi"
    only:
        - RELEASE_STG
    when: manual